const fallback={generatedAt:"2026-09-10T17:56:01+03:00",sourceTime:"17:56:01",temperature:"34.3",humidity:"95.0",timeline:[["00:00:02",0,1],["00:08:04",0,0],["00:09:03",0,1],["08:15:26",1,1],["08:16:03",1,0],["09:59:53",0,0],["10:01:03",0,1],["17:56:01",0,1]],logs:["GEN turned ON: 12:00 AM Till: 08:15 AM (8H15M)","EDL turned ON: 08:15 AM Till: 09:59 AM (1H44M)","GEN turned OFF: 09:59 AM Till: 10:01 AM (2M)","GEN turned ON: 10:01 AM Till: 05:56 PM (7H55M)"],month:{label:"September 2026",edl:35.8,gen:173,none:1}};
const REFRESH_MS=3000,BOOT_MIN_MS=760,bootStartedAt=performance.now();
const findIn=page=>pattern=>page.match(pattern)?.[1]?.trim();
function buildPayload(page,chart,weather){
  const find=findIn(page);
  const logs=[...page.matchAll(/<font[^>]*>(.*?)<\/font>/gis)].map(m=>m[1].replace(/<[^>]+>/g,"").replace(/&nbsp;/g," ").trim()).filter(line=>/^(EDL|GEN) turned (ON|OFF):/i.test(line));
  const entries=normalizeTimeline(chart.rows.map(row=>[row.c[0].v.join(":"),Number(row.c[1].v),Number(row.c[2].v)]));
  const monthLabel=find(/<dtitle>([A-Za-z]+\s+\d{4})\s+statistics<\/dtitle>/i)||"Current month";
  const pie=[...page.matchAll(/y:\s*([\d.]+),\s*name:\s*"(EDL|GEN|No Power)"/g)].reduce((all,[,value,name])=>({...all,[name]:Number(value)}),{});
  return{
    generatedAt:new Date().toISOString(),
    sourceTime:find(/Updated:\s*([\d:]+)/i)||entries.at(-1)?.[0]||"—",
    temperature:weather?.temperature??"—",
    humidity:weather?.humidity??"—",
    timeline:entries,logs,
    month:{label:monthLabel,edl:pie.EDL||0,gen:pie.GEN||0,none:pie["No Power"]||0}
  };
}
async function loadLive(){
  const response=await fetch(`${PUSH_SENDER_URL}/v1/live`,{cache:"no-store",signal:AbortSignal.timeout(9000)});
  if(!response.ok)throw Error(`Live status HTTP ${response.status}`);
  const {page,chart,weather}=await response.json();
  const payload=buildPayload(page,chart,weather);
  if(!payload.timeline.length||payload.sourceTime==="—")throw Error("bad payload");
  return payload;
}
async function loadSnapshot(){
  const response=await fetch(`data/status.json?cache=${Date.now()}`,{cache:"no-store"});
  if(!response.ok)throw Error(`HTTP ${response.status}`);
  return response.json();
}
async function load(){
  try{return await loadLive()}catch{
    try{return await loadSnapshot()}catch{return fallback}
  }
}
const copy={en:{settings:"Settings",language:"Language",notifications:"Notifications",comingSoon:"Coming soon",connected:"Connected",liveStatus:"LIVE STATUS",powerMonitor:"Power Monitor",lastUpdate:"Last update",supplyingNow:"SUPPLYING YOUR HOME NOW",powerRoute:"Power route",currentRoute:"Current route",nationalGrid:"National grid",privateGenerator:"Private generator",homeSupply:"Home supply",environment:"Environment",temperature:"Temperature",humidity:"Humidity",systemState:"System state",monthToDate:"Month to date",trackedHours:"tracked hours",today:"TODAY / WED 10 SEP",powerHistory:"Power history",generator:"Generator",noPower:"No power",eventLog:"EVENT LOG",todaysActivity:"Today’s activity",footerTitle:"HART EL SETT · POWER MONITOR",footerRefresh:"Live data · automatic updates",online:"Online",offline:"Offline",running:"Running",stopped:"Stopped",generatorActive:"Generator active",gridActive:"EDL active",noSupply:"No power available",gridUnavailable:"EDL is unavailable",generatorUnavailable:"Generator is unavailable",generatorNow:"Generator is supplying power now",gridNow:"EDL is supplying power now",events:"events",edl:"EDL"},ar:{settings:"الإعدادات",language:"اللغة",notifications:"الإشعارات",comingSoon:"قريباً",connected:"متصل",liveStatus:"الحالة المباشرة",powerMonitor:"مراقبة الكهرباء",lastUpdate:"آخر تحديث",supplyingNow:"الكهرباء تصل إلى المنزل الآن من",powerRoute:"مسار الكهرباء",currentRoute:"المسار الحالي",nationalGrid:"كهرباء الدولة",privateGenerator:"المولد الخاص",homeSupply:"كهرباء المنزل",environment:"البيئة",temperature:"الحرارة",humidity:"الرطوبة",systemState:"حالة النظام",monthToDate:"إجمالي الشهر",trackedHours:"ساعات مسجلة",today:"اليوم / الأربعاء ١٠ أيلول",powerHistory:"سجل الكهرباء",generator:"المولد",noPower:"لا كهرباء",eventLog:"سجل الأحداث",todaysActivity:"نشاط اليوم",footerTitle:"حرش الست · مراقبة الكهرباء",footerRefresh:"بيانات مباشرة · تحديث تلقائي",online:"متوفرة",offline:"غير متوفرة",running:"يعمل",stopped:"متوقف",generatorActive:"المولد يعمل",gridActive:"كهرباء الدولة متوفرة",noSupply:"لا كهرباء متوفرة",gridUnavailable:"كهرباء الدولة غير متوفرة",generatorUnavailable:"المولد متوقف",generatorNow:"المولد يوفّر الكهرباء الآن",gridNow:"كهرباء الدولة توفّر الكهرباء الآن",events:"أحداث",edl:"كهرباء الدولة"}};
let language=localStorage.getItem("power-language")||"en",currentData=null,sourceInitialized=false;
const $=id=>document.getElementById(id),t=key=>copy[language][key]||copy.en[key]||key;
const NOTIFICATION_PREFERENCE="power-notifications-enabled",NOTIFICATION_SOURCE="power-notifications-source",PUSH_SENDER_URL="https://powerpulse-push.trexghaoui.workers.dev";
let notificationSetupError=false,pushSyncInFlight=null,pushRegistration=null,pushVapidKey=null;
const notificationCopy={en:{on:"On",off:"Off",ready:"Turn on alerts for power-source changes.",enabled:"Alerts are on for source changes, even when this app is closed.",senderError:"Alerts are on, but background delivery could not connect. Try again shortly.",unsupported:"Notifications are not supported in this browser.",pushUnsupported:"Background notifications are not supported in this browser.",denied:"Notifications are blocked in browser settings.",install:"On iPhone, add this app to your Home Screen first.",enabledTitle:"Power alerts enabled",enabledBody:"You will be alerted when the power source changes.",changeTitle:"Power source changed",gridBody:"EDL is now supplying your home.",generatorBody:"Your generator is now supplying your home.",offBody:"There is currently no power supply."},ar:{on:"مفعّلة",off:"متوقفة",ready:"فعّل التنبيهات عند تغيّر مصدر الكهرباء.",enabled:"التنبيهات مفعّلة عند تغيّر المصدر، حتى عند إغلاق التطبيق.",senderError:"التنبيهات مفعّلة، لكن تعذّر الاتصال بالإرسال بالخلفية. حاول مجدداً بعد قليل.",unsupported:"التنبيهات غير مدعومة في هذا المتصفح.",pushUnsupported:"التنبيهات بالخلفية غير مدعومة في هذا المتصفح.",denied:"تم حظر التنبيهات من إعدادات المتصفح.",install:"على iPhone، أضف التطبيق إلى الشاشة الرئيسية أولاً.",enabledTitle:"تم تفعيل تنبيهات الكهرباء",enabledBody:"سيصلك تنبيه عند تغيّر مصدر الكهرباء.",changeTitle:"تغيّر مصدر الكهرباء",gridBody:"كهرباء الدولة توفّر الكهرباء الآن.",generatorBody:"المولد يوفّر الكهرباء الآن.",offBody:"لا يوجد مصدر كهرباء حالياً."}};
const seconds=time=>{const[h,m,s]=time.split(":").map(Number);return h*3600+m*60+s};
const timeLabel=time=>time.slice(0,5);
function powerState(row){return row[1]?"edl":row[2]?"gen":"off"}
function normalizeTimeline(rows){const byTime=new Map();rows.forEach(row=>{const time=String(row[0]||"");if(/^\d{2}:\d{2}:\d{2}$/.test(time)&&Number.isFinite(Number(row[1]))&&Number.isFinite(Number(row[2])))byTime.set(time,[time,Number(row[1])>0?1:0,Number(row[2])>0?1:0])});return [...byTime.values()].sort((a,b)=>seconds(a[0])-seconds(b[0])).filter((row,index,all)=>index===0||powerState(row)!==powerState(all[index-1]))}
function applyLanguage(next){language=next;localStorage.setItem("power-language",next);document.documentElement.lang=next;document.documentElement.dir=next==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll("[data-i18n-aria]").forEach(el=>el.setAttribute("aria-label",t(el.dataset.i18nAria)));document.querySelectorAll(".language-option").forEach(el=>el.classList.toggle("is-selected",el.dataset.language===next));sendNotificationPreference(notificationsEnabled());if(notificationsEnabled())syncPushSubscription(false).then(()=>{notificationSetupError=false;updateNotificationUI()}).catch(()=>{notificationSetupError=true;updateNotificationUI()});updateNotificationUI();if(currentData)render(currentData)}
function setState(data){const[,edl,rawGen]=data.timeline.at(-1),gridOn=Boolean(edl),genOn=!gridOn&&Boolean(rawGen),source=gridOn?t("edl"):genOn?t("generator"):t("noPower"),edlCable=$("cable-edl"),genCable=$("cable-gen");$("edl-card").classList.toggle("is-active",gridOn);$("edl-card").classList.toggle("grid-active",gridOn);$("gen-card").classList.toggle("is-active",genOn);$("edl-state").textContent=gridOn?t("online"):t("offline");$("gen-state").textContent=genOn?t("running"):t("stopped");edlCable.classList.toggle("is-active",gridOn);genCable.classList.toggle("is-active",genOn);const home=$("home-module");home.classList.toggle("on-grid",gridOn);home.classList.toggle("on-gen",genOn);home.classList.toggle("off",!gridOn&&!genOn);$("home-source").textContent=source;$("route-live").classList.toggle("is-live",gridOn||genOn);$("route-detail").textContent=gridOn?t("gridNow"):genOn?t("generatorNow"):t("noSupply");$("temperature").textContent=`${data.temperature}°`;$("humidity").innerHTML=`${data.humidity}<span>%</span>`;const locale=language==="ar"?"ar-LB":"en-GB";$("snapshot-time").textContent=new Intl.DateTimeFormat(locale,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Beirut"}).format(new Date(data.generatedAt)).replace(","," ·").toUpperCase();let start=data.timeline.at(-1)[0];for(let i=data.timeline.length-2;i>=0;i--){const rowGrid=Boolean(data.timeline[i][1]),rowGen=!rowGrid&&Boolean(data.timeline[i][2]);if(rowGrid!==gridOn||rowGen!==genOn)break;start=data.timeline[i][0]}$("route-time").textContent=`${timeLabel(start)} — ${data.sourceTime.slice(0,5)}`}
function segment(track,className,start,end){const node=document.createElement("span");node.className=`segment ${className}`;node.style.left=`${seconds(start)/864}%`;node.style.width=`${Math.max(.18,(seconds(end)-seconds(start))/864)}%`;track.append(node)}
function renderHistory(data){["edl-track","gen-track","none-track"].forEach(id=>$(id).replaceChildren());data.timeline.forEach((row,i)=>{const[time,edl,rawGen]=row,end=data.timeline[i+1]?.[0]||time,gridOn=Boolean(edl),genOn=!gridOn&&Boolean(rawGen);if(gridOn)segment($("edl-track"),"edl-segment",time,end);if(genOn)segment($("gen-track"),"gen-segment",time,end);if(!gridOn&&!genOn)segment($("none-track"),"none-segment",time,end)})}
function renderMonth(data){const v=data.month,total=v.edl+v.gen+v.none;$("tracked-hours").textContent=total.toFixed(1);$("month-key").innerHTML=[[t("generator"),v.gen],[t("edl"),v.edl],[t("noPower"),v.none]].map(([label,value])=>`<div class="breakdown-item"><b>${label}</b><small>${value.toFixed(1)} h · ${(value/total*100).toFixed(0)}%</small></div>`).join("")}
function renderEvents(data){const events=data.logs.map(log=>{const match=log.match(/^(EDL|GEN) turned (ON|OFF):\s*(\d{1,2}:\d{2}\s*[AP]M)(?:\s+Till:\s*(.*))?$/i);return match&&{source:match[1].toUpperCase(),on:match[2].toUpperCase()==="ON",time:match[3],until:match[4]}}).filter(Boolean);$("event-list").replaceChildren();events.forEach(event=>{const time=new Date(`2000-01-01 ${event.time}`).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",hour12:false}),li=document.createElement("li"),kind=event.source==="EDL"?"edl":event.on?"gen":"none";li.className=`event ${kind}`;li.innerHTML=`<time>${time}</time><p><strong>${event.source} turned ${event.on?"ON":"OFF"}: ${event.time}</strong><small>${event.until?`Until ${event.until}`:"Active now"}</small></p>`;$("event-list").append(li)});$("event-count").textContent=`${events.length} ${t("events")}`}
function sourceKey(data){const latest=data.timeline[data.timeline.length-1]||[];return latest[1]?"grid":latest[2]?"generator":"off"}
function supportsNotifications(){return "Notification"in window&&"serviceWorker"in navigator}
function supportsPush(){return supportsNotifications()&&"PushManager"in window}
function isAppleMobile(){return /iPhone|iPad|iPod/.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1)}
function isStandalone(){return window.matchMedia("(display-mode: standalone)").matches||window.navigator.standalone===true}
function notificationsEnabled(){return supportsNotifications()&&Notification.permission==="granted"&&localStorage.getItem(NOTIFICATION_PREFERENCE)==="true"}
function sendNotificationPreference(enabled){if(!("serviceWorker"in navigator))return;navigator.serviceWorker.ready.then(reg=>reg.active?.postMessage({type:"notification-preference",enabled,language})).catch(()=>{})}
function keyBytes(base64url){const padded=base64url+"=".repeat((4-base64url.length%4)%4),binary=atob(padded.replace(/-/g,"+").replace(/_/g,"/"));return Uint8Array.from(binary,char=>char.charCodeAt(0))}
async function senderConfig(){if(pushVapidKey)return{vapidPublicKey:pushVapidKey};const response=await fetch(`${PUSH_SENDER_URL}/v1/config`,{cache:"no-store"});if(!response.ok)throw Error(`Push sender HTTP ${response.status}`);const config=await response.json();if(typeof config.vapidPublicKey!=="string"||config.vapidPublicKey.length<80)throw Error("Push sender returned no VAPID key");pushVapidKey=config.vapidPublicKey;return config}
function reportPushDiagnostic(stage,detail=""){fetch(`${PUSH_SENDER_URL}/v1/diagnostics`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({stage,detail})}).catch(()=>{})}
async function savePushSubscription(subscription,announce,created){const response=await fetch(`${PUSH_SENDER_URL}/v1/subscriptions`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({subscription:subscription.toJSON(),language,announce:announce||created})});if(!response.ok)throw Error(`Push registration HTTP ${response.status}`);return response.json()}
async function registerPushSubscription(announce=false){if(!supportsPush())throw Error("Push is unavailable");const registration=pushRegistration||await navigator.serviceWorker.ready;let subscription=await registration.pushManager.getSubscription(),created=false;if(!subscription){const {vapidPublicKey}=await senderConfig();subscription=await registration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(vapidPublicKey).buffer});created=true}return savePushSubscription(subscription,announce,created)}
function syncPushSubscription(announce=false,userGesture=false){if(pushSyncInFlight)return pushSyncInFlight;const attempt=userGesture&&pushRegistration&&pushVapidKey?pushRegistration.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:keyBytes(pushVapidKey).buffer}).then(subscription=>savePushSubscription(subscription,announce,false)):registerPushSubscription(announce);pushSyncInFlight=attempt.then(result=>{reportPushDiagnostic("registered");return result},error=>{reportPushDiagnostic("registration-failed",error?.name||"unknown");throw error}).finally(()=>{pushSyncInFlight=null});return pushSyncInFlight}
async function removePushSubscription(){if(!supportsPush())return;const registration=await navigator.serviceWorker.ready,subscription=await registration.pushManager.getSubscription();if(!subscription)return;try{await fetch(`${PUSH_SENDER_URL}/v1/subscriptions`,{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({endpoint:subscription.endpoint})})}catch{/* Revoking the browser subscription still prevents future delivery. */}finally{await subscription.unsubscribe()}}
async function syncBackgroundChecks(enabled){if(!("serviceWorker"in navigator))return;try{const reg=await navigator.serviceWorker.ready;if(!("periodicSync"in reg))return;if(enabled){await reg.periodicSync.register("power-status-check",{minInterval:15*60*1000})}else{const tags=await reg.periodicSync.getTags();if(tags.includes("power-status-check"))await reg.periodicSync.unregister("power-status-check")}}catch{/* Background refresh is best effort and browser controlled. */}}
async function showPowerNotification(title,body){try{const reg=await navigator.serviceWorker.ready;await reg.showNotification(title,{body,icon:"icon.svg",badge:"icon.svg",tag:"hart-el-sett-power",renotify:true,data:{url:reg.scope}})}catch{/* Permission or browser support changed while the app was open. */}}
function updateNotificationUI(){const toggle=$("notifications-toggle"),label=$("notifications-toggle-label"),status=$("notification-status");if(!toggle||!label||!status)return;const n=notificationCopy[language];const supported=supportsNotifications(),pushSupported=supportsPush(),appleInstallNeeded=supported&&isAppleMobile()&&!isStandalone(),permission=supported?Notification.permission:"denied",enabled=notificationsEnabled();toggle.setAttribute("aria-checked",String(enabled));label.textContent=enabled?n.on:n.off;toggle.disabled=!supported||!pushSupported||permission==="denied"||appleInstallNeeded;if(!supported)status.textContent=n.unsupported;else if(!pushSupported)status.textContent=n.pushUnsupported;else if(appleInstallNeeded)status.textContent=n.install;else if(permission==="denied")status.textContent=n.denied;else status.textContent=enabled?(notificationSetupError?n.senderError:n.enabled):n.ready}
async function toggleNotifications(){if(notificationsEnabled()){localStorage.removeItem(NOTIFICATION_PREFERENCE);notificationSetupError=false;sendNotificationPreference(false);syncBackgroundChecks(false);try{await removePushSubscription()}catch{/* Local preference remains off if the browser refuses an unsubscribe. */}updateNotificationUI();return}if(!supportsPush()||(isAppleMobile()&&!isStandalone())||Notification.permission==="denied"){updateNotificationUI();return}const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission!=="granted"){updateNotificationUI();return}localStorage.setItem(NOTIFICATION_PREFERENCE,"true");if(currentData)localStorage.setItem(NOTIFICATION_SOURCE,sourceKey(currentData));sendNotificationPreference(true);syncBackgroundChecks(true);try{await syncPushSubscription(true,true);notificationSetupError=false}catch{notificationSetupError=true}updateNotificationUI()}
function notifySourceChange(data){if(!notificationsEnabled())return;const current=sourceKey(data);if(!sourceInitialized){sourceInitialized=true;localStorage.setItem(NOTIFICATION_SOURCE,current);return}const previous=localStorage.getItem(NOTIFICATION_SOURCE);if(!previous||previous===current)return;localStorage.setItem(NOTIFICATION_SOURCE,current);const n=notificationCopy[language],body=current==="grid"?n.gridBody:current==="generator"?n.generatorBody:n.offBody;showPowerNotification(n.changeTitle,body)}
function render(data){currentData=data;setState(data);renderHistory(data);renderMonth(data);renderEvents(data);notifySourceChange(data);if(!document.body.classList.contains("app-ready"))setTimeout(()=>document.body.classList.add("app-ready"),Math.max(0,BOOT_MIN_MS-(performance.now()-bootStartedAt)))}
let refreshing=false;
async function refresh(){if(refreshing)return;refreshing=true;try{render(await load())}finally{refreshing=false}}
applyLanguage(language);refresh();
setInterval(refresh,REFRESH_MS);
const settings=$("settings-button"),panel=$("settings-panel");settings.addEventListener("click",()=>{const open=!panel.hidden;panel.hidden=open;settings.setAttribute("aria-expanded",String(!open))});document.querySelectorAll(".language-option").forEach(button=>button.addEventListener("click",()=>{applyLanguage(button.dataset.language);panel.hidden=true;settings.setAttribute("aria-expanded","false")}));$("notifications-toggle").addEventListener("click",toggleNotifications);updateNotificationUI();
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js").then(()=>navigator.serviceWorker.ready).then(async registration=>{pushRegistration=registration;reportPushDiagnostic(supportsPush()?"runtime-ready":"push-unavailable",isStandalone()?"standalone":"browser");try{await senderConfig()}catch(error){reportPushDiagnostic("config-failed",error?.name||"unknown")}sendNotificationPreference(notificationsEnabled());if(notificationsEnabled())return syncPushSubscription(false).then(()=>{notificationSetupError=false;updateNotificationUI()}).catch(()=>{notificationSetupError=true;updateNotificationUI()})}).catch(error=>reportPushDiagnostic("service-worker-failed",error?.name||"unknown")));
