const fallback={generatedAt:"2026-09-10T17:56:01+03:00",sourceTime:"17:56:01",temperature:"34.3",humidity:"95.0",timeline:[["00:00:02",0,1],["00:08:04",0,0],["00:09:03",0,1],["08:15:26",1,1],["08:16:03",1,0],["09:59:53",0,0],["10:01:03",0,1],["17:56:01",0,1]],logs:["GEN turned ON: 12:00 AM Till: 08:15 AM (8H15M)","EDL turned ON: 08:15 AM Till: 09:59 AM (1H44M)","GEN turned OFF: 09:59 AM Till: 10:01 AM (2M)","GEN turned ON: 10:01 AM Till: 05:56 PM (7H55M)"],month:{label:"September 2026",edl:35.8,gen:173,none:1}};
const copy={en:{settings:"Settings",language:"Language",notifications:"Notifications",comingSoon:"Coming soon",connected:"Connected",liveStatus:"LIVE STATUS",powerMonitor:"Power Monitor",lastUpdate:"Last update",supplyingNow:"SUPPLYING YOUR HOME NOW",powerRoute:"Power route",currentRoute:"Current route",nationalGrid:"National grid",privateGenerator:"Private generator",homeSupply:"Home supply",environment:"Environment",temperature:"Temperature",humidity:"Humidity",systemState:"System state",monthToDate:"Month to date",trackedHours:"tracked hours",today:"TODAY / WED 10 SEP",powerHistory:"Power history",generator:"Generator",noPower:"No power",eventLog:"EVENT LOG",todaysActivity:"Today’s activity",footerTitle:"HART EL SETT · POWER MONITOR",footerRefresh:"Automatic data refresh enabled",online:"Online",offline:"Offline",running:"Running",stopped:"Stopped",generatorActive:"Generator active",gridActive:"EDL active",noSupply:"No power available",gridUnavailable:"EDL is unavailable",generatorUnavailable:"Generator is unavailable",generatorNow:"Generator is supplying power now",gridNow:"EDL is supplying power now",events:"events",edl:"EDL"},ar:{settings:"الإعدادات",language:"اللغة",notifications:"الإشعارات",comingSoon:"قريباً",connected:"متصل",liveStatus:"الحالة المباشرة",powerMonitor:"مراقبة الكهرباء",lastUpdate:"آخر تحديث",supplyingNow:"الكهرباء تصل إلى المنزل الآن من",powerRoute:"مسار الكهرباء",currentRoute:"المسار الحالي",nationalGrid:"كهرباء الدولة",privateGenerator:"المولد الخاص",homeSupply:"كهرباء المنزل",environment:"البيئة",temperature:"الحرارة",humidity:"الرطوبة",systemState:"حالة النظام",monthToDate:"إجمالي الشهر",trackedHours:"ساعات مسجلة",today:"اليوم / الأربعاء ١٠ أيلول",powerHistory:"سجل الكهرباء",generator:"المولد",noPower:"لا كهرباء",eventLog:"سجل الأحداث",todaysActivity:"نشاط اليوم",footerTitle:"حرش الست · مراقبة الكهرباء",footerRefresh:"تحديث البيانات تلقائياً",online:"متوفرة",offline:"غير متوفرة",running:"يعمل",stopped:"متوقف",generatorActive:"المولد يعمل",gridActive:"كهرباء الدولة متوفرة",noSupply:"لا كهرباء متوفرة",gridUnavailable:"كهرباء الدولة غير متوفرة",generatorUnavailable:"المولد متوقف",generatorNow:"المولد يوفّر الكهرباء الآن",gridNow:"كهرباء الدولة توفّر الكهرباء الآن",events:"أحداث",edl:"كهرباء الدولة"}};
let language=localStorage.getItem("power-language")||"en",currentData=null;
const $=id=>document.getElementById(id),t=key=>copy[language][key]||copy.en[key]||key;
const seconds=time=>{const[h,m,s]=time.split(":").map(Number);return h*3600+m*60+s};
const timeLabel=time=>time.slice(0,5);
function applyLanguage(next){language=next;localStorage.setItem("power-language",next);document.documentElement.lang=next;document.documentElement.dir=next==="ar"?"rtl":"ltr";document.querySelectorAll("[data-i18n]").forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll("[data-i18n-aria]").forEach(el=>el.setAttribute("aria-label",t(el.dataset.i18nAria)));document.querySelectorAll(".language-option").forEach(el=>el.classList.toggle("is-selected",el.dataset.language===next));if(currentData)render(currentData)}
function setState(data){const[,edl,gen]=data.timeline.at(-1),source=edl?t("edl"):gen?t("generator"):t("noPower"),edlCable=$("flow-edl"),genCable=$("flow-gen");$("edl-card").classList.toggle("is-active",Boolean(edl));$("edl-card").classList.toggle("grid-active",Boolean(edl));$("gen-card").classList.toggle("is-active",Boolean(gen));$("edl-state").textContent=edl?t("online"):t("offline");$("gen-state").textContent=gen?t("running"):t("stopped");edlCable.classList.toggle("is-active",Boolean(edl));genCable.classList.toggle("is-active",Boolean(gen));$("active-source").classList.toggle("edl",Boolean(edl));$("active-source").classList.toggle("gen",!edl&&Boolean(gen));$("active-source").classList.toggle("none",!edl&&!gen);$("active-source-name").textContent=source;$("home-source").textContent=source;$("route-detail").textContent=edl?t("gridNow"):gen?t("generatorNow"):t("noSupply");$("temperature").textContent=`${data.temperature}°`;$("humidity").innerHTML=`${data.humidity}<span>%</span>`;const locale=language==="ar"?"ar-LB":"en-GB";$("snapshot-time").textContent=new Intl.DateTimeFormat(locale,{day:"2-digit",month:"short",year:"numeric",hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Beirut"}).format(new Date(data.generatedAt)).replace(","," ·").toUpperCase();let start=data.timeline.at(-1)[0];for(let i=data.timeline.length-2;i>=0;i--){if(data.timeline[i][1]!==edl||data.timeline[i][2]!==gen)break;start=data.timeline[i][0]}$("route-time").textContent=`${timeLabel(start)} — ${data.sourceTime.slice(0,5)}`}
function segment(track,className,start,end){const node=document.createElement("span");node.className=`segment ${className}`;node.style.left=`${seconds(start)/864}%`;node.style.width=`${Math.max(.18,(seconds(end)-seconds(start))/864)}%`;track.append(node)}
function renderHistory(data){["edl-track","gen-track","none-track"].forEach(id=>$(id).replaceChildren());data.timeline.forEach((row,i)=>{const[time,edl,gen]=row,end=data.timeline[i+1]?.[0]||time;if(edl)segment($("edl-track"),"edl-segment",time,end);if(gen)segment($("gen-track"),"gen-segment",time,end);if(!edl&&!gen)segment($("none-track"),"none-segment",time,end)})}
function renderMonth(data){const v=data.month,total=v.edl+v.gen+v.none;$("tracked-hours").textContent=total.toFixed(1);$("month-key").innerHTML=[[t("generator"),v.gen],[t("edl"),v.edl],[t("noPower"),v.none]].map(([label,value])=>`<div class="breakdown-item"><b>${label}</b><small>${value.toFixed(1)} h · ${(value/total*100).toFixed(0)}%</small></div>`).join("")}
function typeFor(log){return log.startsWith("EDL")?"edl":log.includes("OFF")?"none":"gen"}function renderEvents(data){$("event-list").replaceChildren();data.logs.slice(-6).forEach(log=>{const match=log.match(/(?:ON|OFF):\s*(\d{1,2}:\d{2}\s*[AP]M)/i),time=match?new Date(`2000-01-01 ${match[1]}`).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",hour12:false}):"—",li=document.createElement("li");li.className=`event ${typeFor(log)}`;li.innerHTML=`<time>${time}</time><p><strong>${log.replace(/ Till:.*/,"")}</strong><small>${log.includes(" Till:")?"Until "+log.split(" Till:")[1]:""}</small></p>`;$("event-list").append(li)});$("event-count").textContent=`${data.logs.length} ${t("events")}`}
function render(data){currentData=data;setState(data);renderHistory(data);renderMonth(data);renderEvents(data)}
async function load(){try{const r=await fetch(`data/status.json?cache=${Date.now()}`);if(!r.ok)throw Error();return await r.json()}catch{return fallback}}
applyLanguage(language);load().then(render);setInterval(()=>load().then(render),30000);
const settings=$("settings-button"),panel=$("settings-panel");settings.addEventListener("click",()=>{const open=!panel.hidden;panel.hidden=open;settings.setAttribute("aria-expanded",String(!open))});document.querySelectorAll(".language-option").forEach(button=>button.addEventListener("click",()=>{applyLanguage(button.dataset.language);panel.hidden=true;settings.setAttribute("aria-expanded","false")}));
if("serviceWorker"in navigator)window.addEventListener("load",()=>navigator.serviceWorker.register("service-worker.js"));
